# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  IMAGE: ghcr.io/thelonelyghost/net-utils

tasks:
  default:
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64 -t {{ .IMAGE }}:latest .
      - docker push {{ .IMAGE }}:latest
    silent: true
